### ISSUE TITLE
Results of this repo is not as good as those in the paper

### ISSUE THREAD

**Issue by jmuddappa** [sleebapaul/attnGAN#1]
Hi I was wondering how I could improve on the results to get more realistic looking results like that in the AttnGAN paper. Is it possible to increase number of epochs or something?

**Comment by jmuddappa** [comment]
@sleebapaul

**Comment by sleebapaul** [comment]
@jmuddappa Hey I couldn't reply earlier since things were a bit hectic around me. I'm not sure if the algorithm can be improved on a general dataset like MS Coco by increasing the epochs. The "realistic" results mentioned in the paper are produced in birds dataset, which has a very limited context. The MS Coco results are cherrypicked.

**Comment by jmuddappa** [comment]
@sleebapaul Hey, yeah you're right! I closed it cause I figured that out later. Very very few results actually give anything usable from COCO. I have modified the code back to the bird dataset now for "realistic" images. Thank you for the response.

**Comment by jmuddappa** [comment]
@sleebapaul I have one issue - when I type in text and generate an image it's always the same image for same text. Is this a feature of the GAN - shouldn't it be a different image every time we re-run the attnGAN model on a given text input?

**Comment by sleebapaul** [comment]
Well, I think the encoding from the RNN model inside AttnGAN produces the same vector representation each time we input the same sentence. At GAN generator side, this vector is used as latent input. So the output should be the same. Otherwise, the model will lack consistency, isn't it?

**Comment by jmuddappa** [comment]
Yes that makes sense thanks
